server:
  port: 8081
spring:
  application:
    name: gm-service-conten
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.93.184.182:3306/gm_db?characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 10000
    testOnBorrow: true
    testOnReturn: false
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  redis:
    database: 0
    timeout: 0
    host: 47.93.184.182
    port: 6379
    password: 12345
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

